name: hypertext_example
description: hypertext example

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.1
  hypertext:
    path: ..

flutter:
  uses-material-design: true
